name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to CF Pages
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE }}
          accountName: Slavabelik79
          projectName: singularity-forecaster
          directory: .
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}