name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to CF Pages
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE }}
          accountId: c97a8486d857b84b0c73526ba91a0221
          projectName: singularity-forecaster
          directory: .
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}